import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, MessageCircle } from "lucide-react";
import hero from "@/assets/dozzo-hero-tanzania.jpg";
import travellers from "@/assets/safari-travellers.jpg";
import mikumi from "@/assets/mikumi-safari-vehicle.jpg";
import nyerere from "@/assets/nyerere-rufiji.jpg";
import serengeti from "@/assets/serengeti-migration.jpg";
import ngorongoro from "@/assets/ngorongoro-crater.jpg";
import tarangire from "@/assets/tarangire-baobabs.jpg";
import { Button } from "@/components/ui/button";
import { DestinationGrid, Eyebrow, SafariGrid, SectionIntro } from "@/components/safari/content";
import { GalleryGrid } from "@/components/safari/gallery";
import { whatsappUrl } from "@/components/safari/data";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Dozzo Safari — Experience Tanzania. Discover the Wild." },
    { name: "description", content: "Authentic Tanzania safari experiences, from Mikumi day trips to Serengeti and Nyerere adventures." },
    { property: "og:title", content: "Dozzo Safari — Tanzania Safari Experiences" },
    { property: "og:description", content: "Explore Tanzania’s legendary national parks with Dozzo Safari." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }), component: HomePage,
});

function HomePage() {
  const experiences = [
    { title: "Day Safaris", image: mikumi, text: "Focused wildlife journeys for travelers with limited time." },
    { title: "Multi-Day Safaris", image: nyerere, text: "More time in the landscape, with an itinerary shaped around you." },
    { title: "Southern Circuit", image: travellers, text: "Mikumi and Nyerere through Tanzania’s compelling southern routes." },
    { title: "Northern Circuit", image: ngorongoro, text: "Tarangire, Ngorongoro and Serengeti in one iconic region." },
    { title: "Great Migration", image: serengeti, text: "Season-led journeys designed around the herds’ natural movement." },
  ];
  return <>
    <section className="hero-section">
      <img src={hero} alt="Elephants crossing the Tanzanian savannah at sunset" width={1920} height={1088} className="absolute inset-0 size-full object-cover" />
      <div className="absolute inset-0 bg-hero-shade" />
      <div className="site-container relative flex min-h-[calc(100svh-5rem)] items-end pb-16 pt-24 md:items-center md:pb-12">
        <div className="max-w-4xl"><Eyebrow inverse>Welcome to Tanzania</Eyebrow><h1 className="hero-title mt-6 text-hero-foreground">Experience Tanzania.<br /><span className="text-primary">Discover the Wild.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-hero-muted md:text-lg">Explore Tanzania&apos;s legendary national parks with Dozzo Safari — from unforgettable day trips to carefully planned multi-day adventures.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="xl"><Link to="/safaris">Explore Safaris <ArrowRight /></Link></Button><Button asChild variant="glass" size="xl"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp Dozzo</a></Button></div></div>
      </div><div className="absolute bottom-0 right-0 hidden border-l border-t border-hero-foreground/15 bg-header/80 px-8 py-5 backdrop-blur-md md:block"><p className="text-xs font-bold uppercase text-primary">Based in Tanzania</p><p className="mt-1 text-sm text-hero-muted">Local knowledge. Wild journeys.</p></div>
    </section>
    <section className="border-b border-border bg-background py-12"><div className="site-container"><p className="text-xs font-bold uppercase text-muted-foreground">What can I book?</p><div className="mt-6 grid gap-px overflow-hidden bg-border sm:grid-cols-2 lg:grid-cols-5">{experiences.map((item) => <Link key={item.title} to="/safaris" className="group relative isolate min-h-64 overflow-hidden bg-header p-5"><img src={item.image} alt="" loading="lazy" width={1200} height={912} className="absolute inset-0 -z-20 size-full object-cover transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 -z-10 bg-image-shade" /><div className="flex h-full flex-col justify-end"><h2 className="font-display text-xl font-extrabold text-hero-foreground">{item.title}</h2><p className="mt-2 text-xs leading-5 text-hero-muted">{item.text}</p><ArrowRight className="mt-4 size-4 text-primary" /></div></Link>)}</div></div></section>
    <section className="section-space bg-background"><div className="site-container"><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><SectionIntro eyebrow="Curated journeys" title="Safaris shaped around Tanzania’s wild places." text="Choose a short escape or a deeper journey. Every itinerary is a starting point for a safari planned around your time and interests." /><Button asChild variant="light" size="xl"><Link to="/safaris">View all safaris <ArrowRight /></Link></Button></div><div className="mt-12"><SafariGrid limit={3} /></div></div></section>
    <section className="section-space bg-header"><div className="site-container"><SectionIntro inverse eyebrow="Why Dozzo Safari?" title="Tanzania is not just where we travel. It’s home." /><div className="mt-14 grid border-y border-hero-foreground/15 sm:grid-cols-2 lg:grid-cols-4">{["Tanzania-focused experiences","Carefully planned itineraries","Flexible safari options","Personalised safari planning"].map((item, index) => <div key={item} className="border-hero-foreground/15 px-0 py-7 sm:px-6 sm:[&:nth-child(even)]:border-l lg:border-l lg:first:border-l-0"><span className="font-display text-sm font-bold text-primary">0{index + 1}</span><p className="mt-6 max-w-[14rem] font-display text-xl font-bold leading-7 text-hero-foreground">{item}</p></div>)}</div></div></section>
    <section className="section-space bg-warm"><div className="site-container"><SectionIntro eyebrow="Explore Tanzania" title="Five landscapes. Five distinct ways to encounter the wild." text="From the river systems of Nyerere to the open Serengeti, each destination has its own rhythm, wildlife and season." /><div className="mt-12"><DestinationGrid /></div></div></section>
    <section className="grid bg-header lg:grid-cols-2"><div className="relative min-h-[32rem]"><img src={nyerere} alt="Elephants crossing the Rufiji River in Nyerere National Park" loading="lazy" width={1408} height={1008} className="absolute inset-0 size-full object-cover" /></div><div className="flex items-center px-5 py-16 sm:px-10 lg:px-16 xl:px-24"><div className="max-w-xl"><Eyebrow inverse>Southern circuit</Eyebrow><h2 className="section-title mt-5 text-hero-foreground">Discover Southern Tanzania.</h2><p className="mt-6 text-base leading-8 text-hero-muted">Go beyond the usual safari routes and discover Tanzania&apos;s southern wilderness through Mikumi and Nyerere.</p><Button asChild size="xl" className="mt-8"><Link to="/safaris">Explore southern safaris <ArrowRight /></Link></Button></div></div></section>
    <section className="grid bg-background lg:grid-cols-2"><div className="flex items-center px-5 py-16 sm:px-10 lg:px-16 xl:px-24"><div className="max-w-xl"><Eyebrow>Iconic Tanzania</Eyebrow><h2 className="section-title mt-5">The Northern Circuit.</h2><p className="mt-6 text-base leading-8 text-muted-foreground">Link the elephant country of Tarangire with Ngorongoro&apos;s volcanic highlands and the far-reaching Serengeti plains.</p><Button asChild variant="light" size="xl" className="mt-8"><Link to="/safaris">Explore northern safaris <ArrowRight /></Link></Button></div></div><div className="relative min-h-[32rem]"><img src={tarangire} alt="Elephants beneath baobabs in Tarangire National Park" loading="lazy" width={1408} height={1008} className="absolute inset-0 size-full object-cover" /></div></section>
    <section className="relative isolate min-h-[38rem] overflow-hidden bg-header"><img src={serengeti} alt="Wildebeest herds moving across the Serengeti" loading="lazy" width={1408} height={1008} className="absolute inset-0 -z-20 size-full object-cover" /><div className="absolute inset-0 -z-10 bg-hero-shade" /><div className="site-container flex min-h-[38rem] items-center py-16"><div className="max-w-2xl"><Eyebrow inverse>Seasonal spectacle</Eyebrow><h2 className="section-title mt-5 text-hero-foreground">Follow the rhythm of the Great Migration.</h2><p className="mt-6 text-base leading-8 text-hero-muted">The herds move with seasonal rains and grazing. Timing and itinerary are planned around current movement rather than a guaranteed location.</p><Button asChild size="xl" className="mt-8"><Link to="/safaris">Explore migration safaris <ArrowRight /></Link></Button></div></div></section>
    <section className="grid bg-background lg:grid-cols-2"><div className="min-h-[28rem]"><img src={travellers} alt="Guests watching lions with their Tanzanian safari guide" loading="lazy" width={1408} height={1008} className="size-full object-cover" /></div><div className="flex items-center px-5 py-16 sm:px-10 lg:px-16 xl:px-24"><div className="max-w-xl"><Eyebrow>Made personal</Eyebrow><h2 className="section-title mt-5">Your safari starts with a conversation.</h2><p className="mt-6 text-base leading-8 text-muted-foreground">Tell us when you want to travel, what you hope to see and how you like to explore. We’ll help shape an itinerary that makes sense for you.</p><Button asChild size="xl" className="mt-8"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle /> Start planning</a></Button></div></div></section>
    <section className="section-space bg-background"><div className="site-container"><div className="flex items-end justify-between gap-6"><SectionIntro eyebrow="Field notes" title="Moments from Tanzania" /><Button asChild variant="light" className="hidden sm:inline-flex"><Link to="/gallery">View gallery <ArrowRight /></Link></Button></div><div className="mt-10"><GalleryGrid limit={6} /></div></div></section>
    <section className="bg-primary py-16 text-primary-foreground"><div className="site-container flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase">Begin your journey</p><h2 className="mt-3 font-display text-3xl font-extrabold md:text-5xl">Your Safari. Your Tanzania.</h2><p className="mt-4 max-w-2xl text-sm leading-7 opacity-85 md:text-base">Tell us what you want to experience and let us help you plan your Tanzania adventure.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Button asChild variant="dark" size="xl"><Link to="/contact">Plan my safari</Link></Button><Button asChild variant="glass" size="xl"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle /> WhatsApp Dozzo</a></Button></div></div></section>
  </>;
}